################################################################################
# Entry point for the CV generation process								  									 #
################################################################################
# The following Makefile wraps all commands required to generate the CV from   #
# the source data and template, as well as helpers and prerequisites.          #
# To get started run `make`, or `make [command]` to run a specific command.    #
################################################################################
# Full source & links to generated assets is at: https://github.com/lissy93/cv #
# Licensed under the MIT License, ⓒ Alicia Sykes 2024 <aliciasykes.com>       #
################################################################################

# Specify that the targets are not files
.PHONY: all install_requirements validate generate compile clean clean_tex watch

# Define variables for common paths
PYTHON := $(shell which python3 2>/dev/null || which python)
REQUIREMENTS := lib/requirements.txt
SCHEMA := schema.json
RESUME := resume.yml
TEMPLATE := template.jinja
OUTPUT_TEX := tex/resume.tex
OUTPUT_PDF := out/Alicia-Sykes-CV.pdf

all: install_requirements clean validate generate compile

# Install required Python packages
install_requirements:
	$(PYTHON) -m pip install -r $(REQUIREMENTS)

# Validate the resume JSON against the schema
validate:
	$(PYTHON) lib/validate.py --schema $(SCHEMA) --resume $(RESUME)

# Generate the LaTeX file from the template and JSON data
generate:
	$(PYTHON) lib/generate.py --resume $(RESUME) --template $(TEMPLATE) --output $(OUTPUT_TEX)

# Compile the LaTeX file into a PDF
compile:
	$(PYTHON) ./lib/compile.py --input $(OUTPUT_TEX) --output $(OUTPUT_PDF)

# Clean up auxiliary LaTeX files
clean: clean_tex
	rm -f $(OUTPUT_PDF)

# Clean only the auxiliary files generated by LaTeX
clean_tex:
	rm -f tex/*.aux tex/*.log tex/*.out tex/*.toc tex/*.fls tex/*.fdb_latexmk tex/*.synctex.gz

# Helper target to watch for changes and rebuild everything
watch:
	ls $(REQUIREMENTS) $(SCHEMA) $(RESUME) $(TEMPLATE) | entr -c make all
