# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
  push:
    tags: [ 'v*' ]
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:alicia/cv.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
